version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: react-toastify
    versions:
    - 7.0.3
  - dependency-name: "@react-pdf/renderer"
    versions:
    - 2.0.6
  - dependency-name: react-scripts
    versions:
    - 4.0.3
  - dependency-name: react
    versions:
    - 17.0.2
